//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tomato.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tomato.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 要认真填写 的本地化字符串。
        /// </summary>
        public static string EditorCreateContentEmptyCaption {
            get {
                return ResourceManager.GetString("EditorCreateContentEmptyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建填写的标题和详情不能为空 的本地化字符串。
        /// </summary>
        public static string EditorCreateContentEmptyContent {
            get {
                return ResourceManager.GetString("EditorCreateContentEmptyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放弃确认 的本地化字符串。
        /// </summary>
        public static string GiveupTipCaption {
            get {
                return ResourceManager.GetString("GiveupTipCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要丢弃这次番茄时间吗？ 的本地化字符串。
        /// </summary>
        public static string GiveupTipContent {
            get {
                return ResourceManager.GetString("GiveupTipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因反馈 的本地化字符串。
        /// </summary>
        public static string GiveupTipInputCaption {
            get {
                return ResourceManager.GetString("GiveupTipInputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这次放弃的原因是？ 的本地化字符串。
        /// </summary>
        public static string GiveupTipInputContent {
            get {
                return ResourceManager.GetString("GiveupTipInputContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 番茄计划 的本地化字符串。
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除确认 的本地化字符串。
        /// </summary>
        public static string MenuDeleteTipCaption {
            get {
                return ResourceManager.GetString("MenuDeleteTipCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除这个计划吗？ 的本地化字符串。
        /// </summary>
        public static string MenuDeleteTipContent {
            get {
                return ResourceManager.GetString("MenuDeleteTipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停确认 的本地化字符串。
        /// </summary>
        public static string PausePlantTipCaption {
            get {
                return ResourceManager.GetString("PausePlantTipCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停的原因是什么？ 的本地化字符串。
        /// </summary>
        public static string PausePlantTipContent {
            get {
                return ResourceManager.GetString("PausePlantTipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续加油 的本地化字符串。
        /// </summary>
        public static string PlantFinishTipCation {
            get {
                return ResourceManager.GetString("PlantFinishTipCation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还有计划的番茄哟，是否继续？ 的本地化字符串。
        /// </summary>
        public static string PlantFinishTipContent {
            get {
                return ResourceManager.GetString("PlantFinishTipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 劳逸结合会更有效率哟 的本地化字符串。
        /// </summary>
        public static string QueryStartRestTipCaption {
            get {
                return ResourceManager.GetString("QueryStartRestTipCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否开始休息？ 的本地化字符串。
        /// </summary>
        public static string QueryStartRestTipContent {
            get {
                return ResourceManager.GetString("QueryStartRestTipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 番茄生长中 的本地化字符串。
        /// </summary>
        public static string TomatoPlantWindowTitle {
            get {
                return ResourceManager.GetString("TomatoPlantWindowTitle", resourceCulture);
            }
        }
    }
}
